#undef _STDDEF_H
#undef _STD_BOOL_H
#undef _STDARG_H
#undef _NETDB_H
#undef _WCHAR_H
#undef _UNISTD_H
#undef _STDIO_H
#undef _LINUX_POSIX_TYPES_H
#undef _LINUX_LIMITS_H
#undef _LINUX_BYTEORDER_LITTLE_ENDIAN_H
#undef _LINUX_TYPES_H
#undef _LINUX_SWAB_H
#undef _LINUX_IOCTL_H
#undef _XLOCALE_H
#undef _RPC_NETDB_H
#undef _BITS_TIME_H
#undef _BITS_BYTESWAP_H
#undef _BITS_SIGTHREAD_H
#undef __BITS_SOCKET_H
#undef _BITS_SOCKADDR_H
#undef _ASM_X86_BYTEORDER_H
#undef _ASM_X86_POSIX_TYPES_64_H
#undef _ASM_X86_TYPES_H
#undef _ASM_X86_SWAB_H
#undef _SYS_UIO_H
#undef _SYS_UCONTEXT_H
#undef _SYS_TERMIOS_H
#undef _SYS_SELECT_H
#undef _SYS_SYSMACROS_H
#undef _SYS_TIME_H  
#undef _SYS_SYSLOG_H
#undef _GETOPT_H
#undef _SIGNAL_H
#undef _STDINT_H
#undef _TIME_H
#undef __ASM_GENERIC_IOCTLS_H
#undef __ASM_GENERIC_POSIX_TYPES_H
#undef __ASM_GENERIC_IOCTLS_H
#undef _ASM_GENERIC_ERRNO_BASE_H
#undef _ASM_GENERIC_TYPES_H
#undef __ASM_GENERIC_SOCKIOS_H
#undef _ASM_GENERIC_ERRNO_H
#undef _ASM_GENERIC_IOCTL_H
#undef __ASM_GENERIC_SOCKET_H
#undef _ASM_GENERIC_INT_LL64_H
#undef _ERRNO_H
#undef _SYS_PRCTL_H
#undef _LINUX_KD_H
#undef _LINUX_VT_H
#undef _SYS_KD_H
#undef _FNMATCH_H
#undef _SYS_FILE_H
#undef _SYS_RESOURCE_H
#undef _SYSCALL_H
#undef _ASM_X86_UNISTD_32_H
#undef _ASM_X86_UNISTD_X32_H
#undef _ASM_X86_UNISTD_64_H
#undef _SYS_USER_H
#undef _ICONV_H
#undef ZLIB_H
#undef ZCONF_H
#undef _UTIME_H
#undef _PTY_H
#undef _IF_TUNNEL_H_
#undef _LINUX_XATTR_H
#undef _LINUX_SCHED_H
#undef _LINUX_RTC_H_
#undef SOUNDCARD_H
#undef _LINUX_PATCHKEY_H
#undef LINUX_NBD_H
#undef HEADER_MD5_H
#undef HEADER_E_OS2_H
#undef HEADER_SHA_H
#undef _LIBINTL_H
#undef _INTTYPES_H
#undef _LOCALE_H
#undef _BITS_LOCALE_H
#undef _STRINGS_
#undef _DLFCN_H
#undef _SYS_MMAN_H
#undef _LINUX_VT_H
#undef _MALLOC_H
#undef _GLOB_H
#undef _SYS_TIMES_H
#undef _SETJMP_H
#undef _BITS_SETJMP_H
#undef _MNTENT_H
#undef _PATHS_H_
#undef _SYS_STATVFS_H
#undef _SCHED_H
#undef _SYS_MOUNT_H
#undef _SYS_IPC_H
#undef _SYS_SHM_H
#undef _SYS_MSG_H
#undef _SYS_SEM_H
#undef _LINUX_FS_H
#undef _SYS_KLOG_H
#undef _SYS_PERSONALITY_H
#undef __LINUX_NETLINK_H
#undef _LINUX_SOCKET_H
#undef _LINUX_CONST_H
#undef _SYS_STATVFS_H
#undef _LINUX_CAPABILITY_H
#undef _LINUX_HDREG_H
#undef _LINUX_FD_H
#undef _LINUX_MSDOS_FS_H
#undef __LINUX_MAGIC_H__
#undef _SCSI_SG_H
#undef _SCSI_SCSI_H
#undef _SYS_SWAP_H
#undef _RPC_RPC_H
#undef _RPC_AUTH_DES_H
#undef _RPC_AUTH_H
#undef _RPC_AUTH_UNIX_H
#undef _RPC_CLNT_H
#undef _RPC_RPC_H
#undef _RPC_MSG_H
#undef _RPC_SVC_AUTH_H
#undef _RPC_SVC_H
#undef _RPC_TYPES_H
#undef _RPC_XDR_H
#undef _SYS_UN_H
#undef _SYS_PARAM_H
#undef _LINUX_PARAM_H
#undef __ASM_GENERIC_PARAM_H
#undef _RPC_PMAP_CLNT_H
#undef _RPC_PMAP_PROT_H
#undef _INPUT_H
#undef _INPUT_EVENT_CODES_H
#undef _LINUX_ELF_EM_H
#undef _ELF_H
#undef _BYTESWAP_H
#undef _WCTYPE_H
#undef _GRP_H
#undef _LIBGEN_H
#undef _SHADOW_H
#undef _SYS_STATFS_H
#undef _SYS_SYSINFO_H
#undef _LINUX_KERNEL_H
#undef _LINUX_SYSINFO_H
#undef _UTMP_H
#undef _UTMPX_H
#undef _NET_IF_H
#undef _NETINET_ETHER_H
#undef __NETINET_IF_ETHER_H
#undef __NET_ETHERNET_H
#undef _NET_IF_ARP_H
#undef _LINUX_IF_ETHER_H
#undef _LINUX_SOCKIOS_H
#undef __NETPACKET_PACKET_H
#undef _IFADDRS_H
#undef _NETINET_IP6_H
#undef __LINUX_FILTER_H__
#undef __LINUX_BPF_COMMON_H__
#undef __LINUX_IF_PACKET_H
#undef __NETINET_IP_H
#undef __NETINET_UDP_H
#undef _ARPA_TELNET_H
#undef __LINUX_RTNETLINK_H
#undef _LINUX_IF_LINK_H
#undef __LINUX_IF_ADDR_H
#undef __LINUX_NEIGHBOUR_H
#undef _LINUX_IF_ARP_H
#undef _LINUX_NETDEVICE_H
#undef __IF_PACKET_H
#undef _LINUX_IF_VLAN_H_
#undef _LINUX_IF_INFINIBAND_H
#undef _LINUX_IF_H
#undef _LIBC_COMPAT_H
#undef __HDLC_IOCTL_H__
#undef _NETINET_TCP_H
#undef __LINUX_SLIP_H
#undef __LINUX_PKT_SCHED_H
#undef _NET_ROUTE_H
#undef __IF_TUN_H
#undef _LINUX_IF_BONDING_H
#undef _LINUX_IF_BRIDGE_H
#undef _LINUX_IN6_H
#undef _LINUX_ETHTOOL_H
#undef _MATH_H
#undef _SYS_TIMEX_H
#undef _BITS_TIMEX_H
#undef __LINUX_MII_H__
#undef _LINUX_WIRELESS_H
#undef _SYS_SENDFILE_H
#undef _NETINET_ICMP6_H
#undef __NETINET_IP_ICMP_H
#undef _RESOLV_H_
#undef _ARPA_NAMESER_COMPAT_
#undef _EXECINFO_H
#undef _SYS_REBOOT_H
#undef _LINUX_FB_H
#undef _LINUX_I2C_H
#undef __MTD_USER_H__
#undef __MTD_ABI_H__
#undef __LINUX_JFFS2_H__
#undef __UBI_USER_H__
#undef _LINUX_TIMEX_H
#undef _LINUX_TIME_H
#undef _LINUX_WATCHDOG_H
#undef _SYS_INOTIFY_H
#undef _SYS_XATTR_H
#undef _LINUX_MAJOR_H
#undef _MD_U_H
#undef _SYS_MTIO_H
#undef __RFKILL_H
#undef _ASM_GENERIC_TERMIOS_H
#undef __ASM_GENERIC_TERMBITS_H
#undef _LINUX_LOOP_H
#undef _LINUX_STRING_H_
#undef _FEATURES_H
#undef _SYS_CDEFS_H
#undef _BITS_LIBM_SIMD_DECL_STUBS_H
#undef _REGEX_H
#undef _SIGSET_H_types
#undef _SELINUX_AVC_H_
#undef _SELINUX_CONTEXT_H_
#undef _SELINUX_GET_SID_LIST_H_
#undef _SELINUX_GET_DEFAULT_TYPE_H_
#undef _SELABEL_H_
#undef _RESTORECON_H_
#undef _SELINUX_H_
#undef _DMALLOC_H_
#undef _STRUCT_TIMESPEC
#undef _PTHREAD_H

