#undef CLEANUP_acpi
#undef CLEANUP_arp
#undef CLEANUP_arping
#undef CLEANUP_ascii
#undef CLEANUP_base64
#undef CLEANUP_basename
#undef CLEANUP_blkid
#undef CLEANUP_blockdev
#undef CLEANUP_bootchartd
#undef CLEANUP_brctl
#undef CLEANUP_bunzip2
#undef CLEANUP_bzcat
#undef CLEANUP_cal
#undef CLEANUP_cat
#undef CLEANUP_catv
#undef CLEANUP_cd
#undef CLEANUP_chattr
#undef CLEANUP_chcon
#undef CLEANUP_chgrp
#undef CLEANUP_chmod
#undef CLEANUP_chroot
#undef CLEANUP_chrt
#undef CLEANUP_chvt
#undef CLEANUP_cksum
#undef CLEANUP_clear
#undef CLEANUP_cmp
#undef CLEANUP_comm
#undef CLEANUP_compress
#undef CLEANUP_count
#undef CLEANUP_cp
#undef CLEANUP_cpio
#undef CLEANUP_crond
#undef CLEANUP_crontab
#undef CLEANUP_cut
#undef CLEANUP_date
#undef CLEANUP_dd
#undef CLEANUP_deallocvt
#undef CLEANUP_df
#undef CLEANUP_dhcp
#undef CLEANUP_dhcp6
#undef CLEANUP_dhcpd
#undef CLEANUP_diff
#undef CLEANUP_dirname
#undef CLEANUP_dmesg
#undef CLEANUP_dos2unix
#undef CLEANUP_du
#undef CLEANUP_dumpleases
#undef CLEANUP_echo
#undef CLEANUP_eject
#undef CLEANUP_env
#undef CLEANUP_exit
#undef CLEANUP_expand
#undef CLEANUP_expr
#undef CLEANUP_factor
#undef CLEANUP_fallocate
#undef CLEANUP_false
#undef CLEANUP_fdisk
#undef CLEANUP_file
#undef CLEANUP_find
#undef CLEANUP_flock
#undef CLEANUP_fold
#undef CLEANUP_free
#undef CLEANUP_freeramdisk
#undef CLEANUP_fsck
#undef CLEANUP_fsfreeze
#undef CLEANUP_fstype
#undef CLEANUP_fsync
#undef CLEANUP_ftpget
#undef CLEANUP_getenforce
#undef CLEANUP_getfattr
#undef CLEANUP_getprop
#undef CLEANUP_getty
#undef CLEANUP_grep
#undef CLEANUP_groupadd
#undef CLEANUP_groupdel
#undef CLEANUP_groups
#undef CLEANUP_gunzip
#undef CLEANUP_gzip
#undef CLEANUP_head
#undef CLEANUP_hello
#undef CLEANUP_help
#undef CLEANUP_hexedit
#undef CLEANUP_host
#undef CLEANUP_hostid
#undef CLEANUP_hostname
#undef CLEANUP_hwclock
#undef CLEANUP_iconv
#undef CLEANUP_id
#undef CLEANUP_ifconfig
#undef CLEANUP_init
#undef CLEANUP_inotifyd
#undef CLEANUP_insmod
#undef CLEANUP_install
#undef CLEANUP_ionice
#undef CLEANUP_iorenice
#undef CLEANUP_iotop
#undef CLEANUP_ip
#undef CLEANUP_ipcrm
#undef CLEANUP_ipcs
#undef CLEANUP_kill
#undef CLEANUP_killall
#undef CLEANUP_killall5
#undef CLEANUP_klogd
#undef CLEANUP_last
#undef CLEANUP_link
#undef CLEANUP_ln
#undef CLEANUP_load_policy
#undef CLEANUP_log
#undef CLEANUP_logger
#undef CLEANUP_login
#undef CLEANUP_logname
#undef CLEANUP_losetup
#undef CLEANUP_ls
#undef CLEANUP_lsattr
#undef CLEANUP_lsmod
#undef CLEANUP_lsof
#undef CLEANUP_lspci
#undef CLEANUP_lsusb
#undef CLEANUP_makedevs
#undef CLEANUP_md5sum
#undef CLEANUP_mdev
#undef CLEANUP_microcom
#undef CLEANUP_mix
#undef CLEANUP_mkdir
#undef CLEANUP_mke2fs
#undef CLEANUP_mkfifo
#undef CLEANUP_mknod
#undef CLEANUP_mkpasswd
#undef CLEANUP_mkswap
#undef CLEANUP_mktemp
#undef CLEANUP_modinfo
#undef CLEANUP_modprobe
#undef CLEANUP_more
#undef CLEANUP_mount
#undef CLEANUP_mountpoint
#undef CLEANUP_mv
#undef CLEANUP_nbd_client
#undef CLEANUP_netcat
#undef CLEANUP_netstat
#undef CLEANUP_nice
#undef CLEANUP_nl
#undef CLEANUP_nohup
#undef CLEANUP_nproc
#undef CLEANUP_nsenter
#undef CLEANUP_od
#undef CLEANUP_oneit
#undef CLEANUP_openvt
#undef CLEANUP_partprobe
#undef CLEANUP_passwd
#undef CLEANUP_paste
#undef CLEANUP_patch
#undef CLEANUP_pgrep
#undef CLEANUP_pidof
#undef CLEANUP_ping
#undef CLEANUP_pivot_root
#undef CLEANUP_pkill
#undef CLEANUP_pmap
#undef CLEANUP_printenv
#undef CLEANUP_printf
#undef CLEANUP_ps
#undef CLEANUP_pwd
#undef CLEANUP_pwdx
#undef CLEANUP_readahead
#undef CLEANUP_readlink
#undef CLEANUP_realpath
#undef CLEANUP_reboot
#undef CLEANUP_renice
#undef CLEANUP_reset
#undef CLEANUP_restorecon
#undef CLEANUP_rev
#undef CLEANUP_rfkill
#undef CLEANUP_rm
#undef CLEANUP_rmdir
#undef CLEANUP_rmmod
#undef CLEANUP_route
#undef CLEANUP_runcon
#undef CLEANUP_sed
#undef CLEANUP_sendevent
#undef CLEANUP_seq
#undef CLEANUP_setenforce
#undef CLEANUP_setfattr
#undef CLEANUP_setprop
#undef CLEANUP_setsid
#undef CLEANUP_sh
#undef CLEANUP_sha1sum
#undef CLEANUP_shred
#undef CLEANUP_skeleton
#undef CLEANUP_skeleton_alias
#undef CLEANUP_sleep
#undef CLEANUP_sort
#undef CLEANUP_split
#undef CLEANUP_start
#undef CLEANUP_stat
#undef CLEANUP_stop
#undef CLEANUP_strings
#undef CLEANUP_su
#undef CLEANUP_sulogin
#undef CLEANUP_swapoff
#undef CLEANUP_swapon
#undef CLEANUP_switch_root
#undef CLEANUP_sync
#undef CLEANUP_sysctl
#undef CLEANUP_syslogd
#undef CLEANUP_tac
#undef CLEANUP_tail
#undef CLEANUP_tar
#undef CLEANUP_taskset
#undef CLEANUP_tcpsvd
#undef CLEANUP_tee
#undef CLEANUP_telnet
#undef CLEANUP_telnetd
#undef CLEANUP_test
#undef CLEANUP_test_human_readable
#undef CLEANUP_test_many_options
#undef CLEANUP_test_scankey
#undef CLEANUP_test_utf8towc
#undef CLEANUP_tftp
#undef CLEANUP_tftpd
#undef CLEANUP_time
#undef CLEANUP_timeout
#undef CLEANUP_top
#undef CLEANUP_touch
#undef CLEANUP_toybox
#undef CLEANUP_tr
#undef CLEANUP_traceroute
#undef CLEANUP_true
#undef CLEANUP_truncate
#undef CLEANUP_tty
#undef CLEANUP_tunctl
#undef CLEANUP_ulimit
#undef CLEANUP_umount
#undef CLEANUP_uname
#undef CLEANUP_uniq
#undef CLEANUP_unix2dos
#undef CLEANUP_unlink
#undef CLEANUP_unshare
#undef CLEANUP_uptime
#undef CLEANUP_useradd
#undef CLEANUP_userdel
#undef CLEANUP_usleep
#undef CLEANUP_uudecode
#undef CLEANUP_uuencode
#undef CLEANUP_vconfig
#undef CLEANUP_vi
#undef CLEANUP_vmstat
#undef CLEANUP_w
#undef CLEANUP_watch
#undef CLEANUP_wc
#undef CLEANUP_wget
#undef CLEANUP_which
#undef CLEANUP_who
#undef CLEANUP_xargs
#undef CLEANUP_xxd
#undef CLEANUP_xzcat
#undef CLEANUP_yes
#undef CLEANUP_zcat
