#define __extension__ /*ignore*/
#define restrict /*ignore*/
#define __restrict /*ignore*/
#define chtype char

#include "listOfGuards.h"
#include "listOfNeeds.h"
#include "listPredefinedMacros.h"
#include "SystemConfig.h"
#include "OPTSTR.h"
#undef FOR_netcat
#undef FOR_microcom
#undef FOR_ftpget
#undef FOR_netstat
#undef FOR_ifconfig
#undef FOR_tunctl
#undef FOR_rfkill
#undef FOR_dd
#undef FOR_lsof
#undef FOR_fold
#undef FOR_compress
#undef FOR_tftpd
#undef FOR_openvt
#undef FOR_tar
#undef FOR_setfattr
#undef FOR_dhcp6
#undef FOR_dumpleases
#undef FOR_tr
#undef FOR_expr
#undef FOR_vi
#undef FOR_ipcs
#undef FOR_gzip
#undef FOR_crontab
#undef FOR_userdel
#undef FOR_groupdel
#undef FOR_tftp
#undef FOR_arping
#undef FOR_telnetd
#undef FOR_more
#undef FOR_klogd
#undef FOR_last
#undef FOR_fsck
#undef FOR_brctl
#undef FOR_diff
#undef FOR_bootchartd
#undef FOR_arp
#undef FOR_dhcpd
#undef FOR_telnet
#undef FOR_useradd
#undef FOR_iconv
#undef FOR_ip
#undef FOR_logger
#undef FOR_watch
#undef FOR_getfattr
#undef FOR_tcpsvd
#undef FOR_getty
#undef FOR_xzcat
#undef FOR_sh
#undef FOR_ipcrm
#undef FOR_host
#undef FOR_wget
#undef FOR_traceroute
#undef FOR_modprobe
#undef FOR_fdisk
#undef FOR_groupadd
#undef FOR_sulogin
#undef FOR_crond
#undef FOR_mke2fs
#undef FOR_ping
#undef FOR_route
#undef FOR_syslogd
#undef FOR_dhcp
#undef FOR_ionice
#undef FOR_lsattr
#undef FOR_chattr
#undef FOR_readlink
#undef FOR_nsenter
#undef FOR_unshare
#undef FOR_nsenter
#undef FOR_hexedit
#undef FOR_dos2unix
#undef FOR_bunzip2
#undef FOR_free
#undef FOR_chcon
#undef FOR_chcon
#undef FOR_hwclock
#undef FOR_fallocate
#undef FOR_xxd
#undef FOR_truncate
#undef FOR_swapon
#undef FOR_rmmod
#undef FOR_vmstat
#undef FOR_eject
#undef FOR_makedevs
#undef FOR_timeout
#undef FOR_login
#undef FOR_pivot_root
#undef FOR_switch_root
#undef FOR_fsync
#undef FOR_lspci
#undef FOR_oneit
#undef FOR_taskset
#undef FOR_fsfreeze
#undef FOR_shred
#undef FOR_mountpoint
#undef FOR_stat
#undef FOR_mix
#undef FOR_chrt
#undef FOR_sysctl
#undef FOR_base64
#undef FOR_mkswap
#undef FOR_acpi
#undef FOR_modinfo
#undef FOR_reboot
#undef FOR_help
#undef FOR_mkpasswd
#undef FOR_nbd_client
#undef FOR_uptime
#undef FOR_pmap
#undef FOR_blockdev
#undef FOR_blkid
#undef FOR_inotifyd
#undef FOR_flock
#undef FOR_losetup
#undef FOR_mknod
#undef FOR_passwd
#undef FOR_su
#undef FOR_mount
#undef FOR_umount
#undef FOR_md5sum
#undef FOR_seq
#undef FOR_dmesg
#undef FOR_pidof
#undef FOR_hostname
#undef FOR_mktemp
#undef FOR_killall
#undef FOR_hostid
#undef FOR_skeleton
#undef FOR_skeleton_alias
#undef FOR_test_many_options
#undef FOR_hello
#undef FOR_test_scankey
#undef FOR_test_human_readable
#undef FOR_expand
#undef FOR_find
#undef FOR_nl
#undef FOR_head
#undef FOR_id
#undef FOR_grep
#undef FOR_nice
#undef FOR_wc
#undef FOR_touch
#undef FOR_sed
#undef FOR_cut
#undef FOR_uniq
#undef FOR_tee
#undef FOR_kill
#undef FOR_killall5
#undef FOR_df
#undef FOR_uudecode
#undef FOR_cmp
#undef FOR_sort
#undef FOR_ulimit
#undef FOR_renice
#undef FOR_split
#undef FOR_cp
#undef FOR_install
#undef FOR_file
#undef FOR_echo
#undef FOR_patch
#undef FOR_chmod
#undef FOR_strings
#undef FOR_printf
#undef FOR_uname
#undef FOR_mkfifo
#undef FOR_comm
#undef FOR_chgrp
#undef FOR_who
#undef FOR_od
#undef FOR_ps
#undef FOR_top
#undef FOR_iotop
#undef FOR_pgrep
#undef FOR_pkill
#undef FOR_cpio
#undef FOR_env
#undef FOR_paste
#undef FOR_xargs
#undef FOR_uuencode
#undef FOR_rm
#undef FOR_du
#undef FOR_cksum
#undef FOR_pwd
#undef FOR_cat
#undef FOR_ln
#undef FOR_tail
#undef FOR_date
#undef FOR_mkdir
#undef FOR_ls
#undef FOR_setenforce
#undef FOR_runcon
#undef FOR_restorecon
#undef FOR_setprop
#undef FOR_getprop
#undef FOR_load_policy
#undef FOR_log
#undef FOR_getenforce
#undef FOR_sendevent
#undef FOR_start
#undef FOR_ascii
#undef FOR_basename
#undef FOR_bzcat
#undef FOR_cal
#undef FOR_catv
#undef FOR_cd
#undef FOR_chroot
#undef FOR_chvt
#undef FOR_clear
#undef FOR_count
#undef FOR_deallocvt
#undef FOR_dirname
#undef FOR_exit
#undef FOR_factor
#undef FOR_false
#undef FOR_freeramdisk
#undef FOR_fstype
#undef FOR_groups
#undef FOR_gunzip
