#undef __need_sigevent_t
#undef __need_timespec
#undef ___need___FILE
#undef __need___va_list
#undef __need_size_t
#undef __need_wchar_t
#undef __need_NULL
#undef __need_wint_t
#undef __need_iswxxx
#undef __need_getopt
#undef __need_time_t
#undef __need_timeval
#undef __need_clock_t
#undef __need_timer_t
#undef __need_clockid_t
#undef __need_siginfo_t
#undef __need_mbstate_t
#undef __need_FILE
#undef __pid_t_defined
#undef __need_schedparam
#undef __defined_schedparam
#undef __uid_t_defined
#undef __gid_t_defined
#undef __mode_t_defined
#undef __key_t_defined
#undef __fsblkcnt_t_defined
#undef __fsfilcnt_t_defined
#undef __fsblkcnt_t_defined
#undef __fsfilcnt_t_defined
#undef __need_iswxxx
#undef __iswxxx_defined
#undef __res_state_defined
#undef __uint32_t_defined
#undef __size_t
