#define KGEN_x25 ((!defined KGENMACRO_CONFIG_INTEGER_16BIT))
#define KGEN_x23 ((!defined KGENMACRO_CONFIG_INTEGER_32BIT))
#define KGEN_x28 ((!defined KGENMACRO_CONFIG_INTEGER_8BIT))
#define KGEN_x34 ((!defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY))
#define KGEN_x32 ((!defined KGENMACRO_CONFIG_BIGINT_CLASSICAL))
#define KGEN_x37 ((!defined KGENMACRO_CONFIG_BIGINT_BARRETT))
#define KGEN_x43 ((!defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM))
#define KGEN_x41 ((!defined KGENMACRO_CONFIG_SSL_PROT_LOW))
#define KGEN_x46 ((!defined KGENMACRO_CONFIG_SSL_PROT_HIGH))
#define KGEN_x52 ((!defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION))
#define KGEN_x50 ((!defined KGENMACRO_CONFIG_SSL_SERVER_ONLY))
#define KGEN_x55 ((!defined KGENMACRO_CONFIG_SSL_ENABLE_CLIENT))
#define KGEN_x58 ((!defined KGENMACRO_CONFIG_SSL_FULL_MODE))
#define KGEN_x61 ((!defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x72 ((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0))
#define KGEN_x70 ((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0))
#define KGEN_x75 ((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0))
#define KGEN_x81 ((!defined KGENMACRO_CONFIG_PLATFORM_CYGWIN))
#define KGEN_x79 ((!defined KGENMACRO_CONFIG_PLATFORM_LINUX))
#define KGEN_x84 ((!defined KGENMACRO_CONFIG_PLATFORM_WIN32))
#define KGEN_x90 ((defined KGENMACRO_CONFIG_INTEGER_32BIT||defined KGENMACRO_CONFIG_INTEGER_16BIT||defined KGENMACRO_CONFIG_INTEGER_8BIT))
#define KGEN_x96 (((KGEN_x61)||(!(KGEN_x90))))
#define KGEN_x95 ((defined KGENMACRO_CONFIG_INTEGER_32BIT||defined KGENMACRO_CONFIG_INTEGER_16BIT||defined KGENMACRO_CONFIG_INTEGER_8BIT||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x91 ((defined KGENMACRO_CONFIG_BIGINT_CLASSICAL||defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY||defined KGENMACRO_CONFIG_BIGINT_BARRETT))
#define KGEN_x101 (((KGEN_x61)||(!(KGEN_x91))))
#define KGEN_x100 ((defined KGENMACRO_CONFIG_BIGINT_CLASSICAL||defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY||defined KGENMACRO_CONFIG_BIGINT_BARRETT||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x93 ((defined KGENMACRO_CONFIG_SSL_PROT_LOW||defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM||defined KGENMACRO_CONFIG_SSL_PROT_HIGH))
#define KGEN_x106 (((KGEN_x61)||(!(KGEN_x93))))
#define KGEN_x105 ((defined KGENMACRO_CONFIG_SSL_PROT_LOW||defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM||defined KGENMACRO_CONFIG_SSL_PROT_HIGH||defined KGENMACRO_CONFIG_SSL_SKELETON_MODE))
#define KGEN_x103 ((defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0))
#define KGEN_x112 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32||(!(KGEN_x103))))
#define KGEN_x111 ((defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0||defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0||(KGEN_x84)))
#define KGEN_x115 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_HAS_CGI))
#define KGEN_x120 ((!(KGEN_x115)))
#define KGEN_x118 (((!defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA)||(KGEN_x115)))
#define KGEN_x129 ((!defined KGENMACRO_CONFIG_HTTP_ENABLE_DIFFERENT_USER))
#define KGEN_x123 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)))
#define KGEN_x132 ((!(KGEN_x123)))
#define KGEN_x136 ((defined KGENMACRO_CONFIG_AXHTTPD&&defined KGENMACRO_CONFIG_HTTP_ENABLE_DIFFERENT_USER))
#define KGEN_x148 ((!(KGEN_x136)))
#define KGEN_x149 ((defined KGENMACRO_CONFIG_HTTP_USER||(KGEN_x148)))
#define KGEN_x147 (((!defined KGENMACRO_CONFIG_HTTP_USER)||(KGEN_x136)))
#define KGEN_x145 ((defined KGENMACRO_CONFIG_PERL_BINDINGS&&defined KGENMACRO_CONFIG_PLATFORM_WIN32))
#define KGEN_x159 ((!(KGEN_x145)))
#define KGEN_x160 ((defined KGENMACRO_CONFIG_PERL_CORE||(KGEN_x159)))
#define KGEN_x158 (((!defined KGENMACRO_CONFIG_PERL_CORE)||(KGEN_x145)))
#define KGEN_x155 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_JAVA_BINDINGS))
#define KGEN_x164 ((!(KGEN_x155)))
#define KGEN_x162 (((!defined KGENMACRO_CONFIG_JAVA_SAMPLES)||(KGEN_x155)))
#define KGEN_x172 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_SSL_EXPIRY_TIME))
#define KGEN_x171 (((!defined KGENMACRO_CONFIG_SSL_EXPIRY_TIME)||(KGEN_x61)))
#define KGEN_x190 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_PERL_BINDINGS))))
#define KGEN_x168 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_PERL_BINDINGS))
#define KGEN_x181 ((!(KGEN_x168)))
#define KGEN_x177 (((!defined KGENMACRO_CONFIG_PERL_SAMPLES)||(KGEN_x168)))
#define KGEN_x214 ((!(defined KGENMACRO_CONFIG_CSHARP_BINDINGS||defined KGENMACRO_CONFIG_VBNET_BINDINGS)))
#define KGEN_x215 ((defined KGENMACRO_CONFIG_DOT_NET_FRAMEWORK_BASE||(KGEN_x214)))
#define KGEN_x210 (((!defined KGENMACRO_CONFIG_DOT_NET_FRAMEWORK_BASE)||defined KGENMACRO_CONFIG_CSHARP_BINDINGS||defined KGENMACRO_CONFIG_VBNET_BINDINGS))
#define KGEN_x218 ((!defined KGENMACRO_CONFIG_AXHTTPD))
#define KGEN_x234 (((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_SESSION_CACHE_SIZE))
#define KGEN_x230 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_SESSION_CACHE_SIZE)))
#define KGEN_x223 ((!defined KGENMACRO_CONFIG_HTTP_IS_DAEMON))
#define KGEN_x246 ((!defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT))
#define KGEN_x247 ((defined KGENMACRO_CONFIG_SSL_X509_COMMON_NAME||(KGEN_x246)))
#define KGEN_x245 (((!defined KGENMACRO_CONFIG_SSL_X509_COMMON_NAME)||defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT))
#define KGEN_x242 (((!defined KGENMACRO_CONFIG_SSL_SERVER_ONLY)&&(KGEN_x61)))
#define KGEN_x256 ((!(KGEN_x242)))
#define KGEN_x257 ((defined KGENMACRO_CONFIG_X509_MAX_CA_CERTS||(KGEN_x256)))
#define KGEN_x255 (((!defined KGENMACRO_CONFIG_X509_MAX_CA_CERTS)||(KGEN_x242)))
#define KGEN_x186 ((!defined KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY))
#define KGEN_x187 (((KGEN_x186)&&(KGEN_x61)))
#define KGEN_x262 (((!(KGEN_x187))||defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_LOCATION))
#define KGEN_x261 (((!defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_LOCATION)||(KGEN_x187)))
#define KGEN_x253 (((!defined KGENMACRO_CONFIG_HTTP_HAS_CGI)||(KGEN_x123)))
#define KGEN_x274 (((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_PORT))
#define KGEN_x271 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_PORT)))
#define KGEN_x289 (((KGEN_x61)||(KGEN_x186)))
#define KGEN_x293 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x289)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY)))
#define KGEN_x267 ((!defined KGENMACRO_CONFIG_HTTP_HAS_IPV6))
#define KGEN_x297 (((!(defined KGENMACRO_CONFIG_AXHTTPD&&(!defined KGENMACRO_CONFIG_PLATFORM_WIN32)))&&(KGEN_x267)))
#define KGEN_x300 (((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_TIMEOUT))
#define KGEN_x299 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_TIMEOUT)))
#define KGEN_x288 ((!defined KGENMACRO_CONFIG_SSL_TEST))
#define KGEN_x286 ((defined KGENMACRO_CONFIG_SSL_FULL_MODE&&(KGEN_x246)))
#define KGEN_x308 (((KGEN_x61)&&defined KGENMACRO_CONFIG_BIGINT_KARATSUBA))
#define KGEN_x315 ((!(KGEN_x308)))
#define KGEN_x316 ((defined KGENMACRO_MUL_KARATSUBA_THRESH||(KGEN_x315)))
#define KGEN_x314 (((!defined KGENMACRO_MUL_KARATSUBA_THRESH)||(KGEN_x308)))
#define KGEN_x311 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0))
#define KGEN_x325 ((!(KGEN_x311)))
#define KGEN_x326 ((defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0_BASE||(KGEN_x325)))
#define KGEN_x324 (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0_BASE)||(KGEN_x311)))
#define KGEN_x312 ((!defined KGENMACRO_CONFIG_BIGINT_KARATSUBA))
#define KGEN_x360 (((KGEN_x84)||(!defined KGENMACRO_CONFIG_USE_DEV_URANDOM)))
#define KGEN_x364 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&(KGEN_x360)&&(defined KGENMACRO_CONFIG_PLATFORM_WIN32||defined KGENMACRO_CONFIG_USE_DEV_URANDOM)))
#define KGEN_x366 (((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_HTTPS_PORT))
#define KGEN_x363 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_HTTPS_PORT)))
#define KGEN_x384 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_CSHARP_BINDINGS))))
#define KGEN_x379 ((!defined KGENMACRO_CONFIG_LUA_BINDINGS))
#define KGEN_x380 ((defined KGENMACRO_CONFIG_LUA_CORE||(KGEN_x379)))
#define KGEN_x378 (((!defined KGENMACRO_CONFIG_LUA_CORE)||defined KGENMACRO_CONFIG_LUA_BINDINGS))
#define KGEN_x395 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_DIRECTORIES)))
#define KGEN_x412 ((defined KGENMACRO_CONFIG_AXHTTPD&&(defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_STATIC_BUILD))))
#define KGEN_x390 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_LUA_BINDINGS))
#define KGEN_x398 ((!(KGEN_x390)))
#define KGEN_x393 (((!defined KGENMACRO_CONFIG_LUA_SAMPLES)||(KGEN_x390)))
#define KGEN_x425 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_HAS_AUTHORIZATION)))
#define KGEN_x437 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_JAVA_BINDINGS))))
#define KGEN_x420 (((!defined KGENMACRO_CONFIG_BIGINT_SLIDING_WINDOW)||(KGEN_x61)))
#define KGEN_x452 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x420)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_BIGINT_SLIDING_WINDOW)))
#define KGEN_x480 ((defined KGENMACRO_CONFIG_HTTP_VERBOSE||(!(defined KGENMACRO_CONFIG_AXHTTPD&&defined KGENMACRO_CONFIG_SSL_FULL_MODE))))
#define KGEN_x451 ((defined KGENMACRO_CONFIG_AXHTTPD&&defined KGENMACRO_CONFIG_SSL_FULL_MODE))
#define KGEN_x447 ((!defined KGENMACRO_CONFIG_HTTP_VERBOSE))
#define KGEN_x460 (((!defined KGENMACRO_CONFIG_BIGINT_CRT)||(KGEN_x61)))
#define KGEN_x488 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x460)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_BIGINT_CRT)))
#define KGEN_x493 ((defined KGENMACRO_CONFIG_BINDINGS&&(defined KGENMACRO_CONFIG_BINDINGS||(!defined KGENMACRO_CONFIG_VBNET_BINDINGS))))
#define KGEN_x282 (((KGEN_x186)&&defined KGENMACRO_CONFIG_SSL_HAS_PEM))
#define KGEN_x484 (((!(KGEN_x282))||defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_PASSWORD))
#define KGEN_x478 (((!defined KGENMACRO_CONFIG_SSL_PRIVATE_KEY_PASSWORD)||(KGEN_x282)))
#define KGEN_x468 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_CSHARP_BINDINGS))
#define KGEN_x487 ((!(KGEN_x468)))
#define KGEN_x474 (((!defined KGENMACRO_CONFIG_CSHARP_SAMPLES)||(KGEN_x468)))
#define KGEN_x517 ((defined KGENMACRO_CONFIG_SAMPLES||(!defined KGENMACRO_CONFIG_C_SAMPLES)))
#define KGEN_x499 ((!defined KGENMACRO_CONFIG_SAMPLES))
#define KGEN_x515 (((KGEN_x120)||defined KGENMACRO_CONFIG_HTTP_CGI_LAUNCHER))
#define KGEN_x514 (((!defined KGENMACRO_CONFIG_HTTP_CGI_LAUNCHER)||(KGEN_x115)))
#define KGEN_x110 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA))
#define KGEN_x116 ((!(KGEN_x110)))
#define KGEN_x528 (((KGEN_x116)||defined KGENMACRO_CONFIG_HTTP_LUA_PREFIX))
#define KGEN_x527 (((!defined KGENMACRO_CONFIG_HTTP_LUA_PREFIX)||(KGEN_x110)))
#define KGEN_x533 (((KGEN_x246)||defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME))
#define KGEN_x532 ((defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT||(!defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME)))
#define KGEN_x530 ((!defined KGENMACRO_CONFIG_WIN32_USE_CRYPTO_LIB))
#define KGEN_x547 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&(defined KGENMACRO_CONFIG_PLATFORM_WIN32||(KGEN_x530))))
#define KGEN_x562 (((KGEN_x61)&&defined KGENMACRO_CONFIG_SSL_FULL_MODE&&(!((KGEN_x61)&&(!defined KGENMACRO_CONFIG_SSL_FULL_MODE)))))
#define KGEN_x564 ((!(KGEN_x562)))
#define KGEN_x567 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&((!defined KGENMACRO_CONFIG_SSL_HAS_PEM)||(KGEN_x562))&&(defined KGENMACRO_CONFIG_SSL_HAS_PEM||(KGEN_x564))))
#define KGEN_x553 (((KGEN_x246)||defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_NAME))
#define KGEN_x552 ((defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT||(!defined KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_NAME)))
#define KGEN_x558 (((KGEN_x159)||defined KGENMACRO_CONFIG_PERL_LIB))
#define KGEN_x557 (((!defined KGENMACRO_CONFIG_PERL_LIB)||(KGEN_x145)))
#define KGEN_x587 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&((!defined KGENMACRO_CONFIG_SSL_USE_PKCS12)||(KGEN_x562))&&(defined KGENMACRO_CONFIG_SSL_USE_PKCS12||(!(KGEN_x562)))))
#define KGEN_x555 (((!defined KGENMACRO_CONFIG_BIGINT_SQUARE)||(KGEN_x61)))
#define KGEN_x580 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x555)&&(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE||defined KGENMACRO_CONFIG_BIGINT_SQUARE)))
#define KGEN_x566 ((!defined KGENMACRO_CONFIG_HTTP_BUILD_LUA))
#define KGEN_x591 ((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA&&((KGEN_x566)||(KGEN_x110))))
#define KGEN_x579 (((!(defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0))||defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0_BASE))
#define KGEN_x122 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0))
#define KGEN_x577 (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_7_0_BASE)||(KGEN_x122)))
#define KGEN_x574 ((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_VBNET_BINDINGS))
#define KGEN_x594 ((!(KGEN_x574)))
#define KGEN_x589 (((!defined KGENMACRO_CONFIG_VBNET_SAMPLES)||(KGEN_x574)))
#define KGEN_x605 (((KGEN_x120)||defined KGENMACRO_CONFIG_HTTP_CGI_EXTENSIONS))
#define KGEN_x604 (((!defined KGENMACRO_CONFIG_HTTP_CGI_EXTENSIONS)||(KGEN_x115)))
#define KGEN_x614 (((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_WEBROOT))
#define KGEN_x613 ((defined KGENMACRO_CONFIG_AXHTTPD||(!defined KGENMACRO_CONFIG_HTTP_WEBROOT)))
#define KGEN_x382 (((KGEN_x61)&&defined KGENMACRO_CONFIG_BIGINT_KARATSUBA&&defined KGENMACRO_CONFIG_BIGINT_SQUARE))
#define KGEN_x619 (((!(KGEN_x382))||defined KGENMACRO_SQU_KARATSUBA_THRESH))
#define KGEN_x618 (((!defined KGENMACRO_SQU_KARATSUBA_THRESH)||(KGEN_x382)))
#define KGEN_x637 (((!(defined KGENMACRO_CONFIG_BINDINGS&&(!defined KGENMACRO_CONFIG_PLATFORM_WIN32)))&&(KGEN_x379)))
#define KGEN_x610 ((defined KGENMACRO_CONFIG_BINDINGS&&(KGEN_x84)))
#define KGEN_x410 (((!defined KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT)&&(!defined KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY)&&(KGEN_x61)))
#define KGEN_x632 (((!(KGEN_x410))||defined KGENMACRO_CONFIG_SSL_X509_CERT_LOCATION))
#define KGEN_x628 (((!defined KGENMACRO_CONFIG_SSL_X509_CERT_LOCATION)||(KGEN_x410)))
#define KGEN_x655 ((!((!defined KGENMACRO_CONFIG_SSL_SKELETON_MODE)&&(!defined KGENMACRO_CONFIG_DEBUG))))
#define KGEN_x656 (((KGEN_x61)&&defined KGENMACRO_CONFIG_DEBUG&&(KGEN_x655)))
#define KGEN_x661 ((defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&((!defined KGENMACRO_CONFIG_BIGINT_CHECK_ON)||(KGEN_x656))&&(defined KGENMACRO_CONFIG_BIGINT_CHECK_ON||(!(KGEN_x656)))))
#define KGEN_x647 (((!(defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0))||defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0_BASE))
#define KGEN_x434 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32&&defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0))
#define KGEN_x646 (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0_BASE)||(KGEN_x434)))
#define KGEN_x652 (((!defined KGENMACRO_CONFIG_JAVA_BINDINGS)||defined KGENMACRO_CONFIG_JAVA_HOME))
#define KGEN_x651 ((defined KGENMACRO_CONFIG_JAVA_BINDINGS||(!defined KGENMACRO_CONFIG_JAVA_HOME)))
#define KGEN_x666 ((defined KGENMACRO_CONFIG_PLATFORM_WIN32||defined KGENMACRO_PREFIX))
#define KGEN_x665 (((KGEN_x84)||(!defined KGENMACRO_PREFIX)))
#define KGEN_x635 ((!defined KGENMACRO_CONFIG_DEBUG))
#define KGEN_x650 (((KGEN_x84)&&(KGEN_x635)))
#define KGEN_x668 ((!(KGEN_x650)))
#define KGEN_x663 (((!defined KGENMACRO_CONFIG_STRIP_UNWANTED_SECTIONS)||(KGEN_x650)))
#define KGEN_x678 ((!defined KGENMACRO_CONFIG_PERFORMANCE_TESTING))
#define KGEN_x706 ((defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION&&(defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION||(KGEN_x678))))
#if (((KGEN_x299)&&(KGEN_x300)))
#ifdef KGENMACRO_CONFIG_HTTP_TIMEOUT
#define CONFIG_HTTP_TIMEOUT 300
#else
#define CONFIG_HTTP_TIMEOUT 0
#endif
#endif
#if (((KGEN_x552)&&(KGEN_x553)))
#ifdef KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_NAME
#define CONFIG_SSL_X509_ORGANIZATION_NAME "X"
#else
#define CONFIG_SSL_X509_ORGANIZATION_NAME ""
#endif
#endif
#if (((KGEN_x50)||(KGEN_x52))) && (((KGEN_x50)||(KGEN_x55))) && (((KGEN_x50)||(KGEN_x58))) && (((KGEN_x50)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_SERVER_ONLY
#define CONFIG_SSL_SERVER_ONLY 1
#else
#undef CONFIG_SSL_SERVER_ONLY
#endif
#endif
#if (((KGEN_x651)&&(KGEN_x652)))
#ifdef KGENMACRO_CONFIG_JAVA_HOME
#define CONFIG_JAVA_HOME "/usr/lib/jvm/java-7-openjdk-amd64"
#else
#define CONFIG_JAVA_HOME ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SSL_FULL_MODE&&(KGEN_x246)&&((KGEN_x288)||(KGEN_x286)))||((!(KGEN_x286))&&(KGEN_x288))))
#ifdef KGENMACRO_CONFIG_SSL_TEST
#define CONFIG_SSL_TEST 1
#else
#undef CONFIG_SSL_TEST
#endif
#endif
#if (((KGEN_x41)||(KGEN_x43))) && (((KGEN_x41)||(KGEN_x46)))
#ifdef KGENMACRO_CONFIG_SSL_PROT_LOW
#define CONFIG_SSL_PROT_LOW 1
#else
#undef CONFIG_SSL_PROT_LOW
#endif
#endif
#if (((KGEN_x210)&&(KGEN_x215)))
#ifdef KGENMACRO_CONFIG_DOT_NET_FRAMEWORK_BASE
#define CONFIG_DOT_NET_FRAMEWORK_BASE "c:\\WINDOWS\\Microsoft.NET\\Framework\\v2.0.50727"
#else
#define CONFIG_DOT_NET_FRAMEWORK_BASE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x395))||((KGEN_x218)&&(KGEN_x395)&&((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_DIRECTORIES))))
#ifdef KGENMACRO_CONFIG_HTTP_DIRECTORIES
#define CONFIG_HTTP_DIRECTORIES 1
#else
#undef CONFIG_HTTP_DIRECTORIES
#endif
#endif
#if (((KGEN_x158)&&(KGEN_x160)))
#ifdef KGENMACRO_CONFIG_PERL_CORE
#define CONFIG_PERL_CORE "c:\\perl\\lib\\CORE"
#else
#define CONFIG_PERL_CORE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_VBNET_BINDINGS&&(KGEN_x589))||((KGEN_x594)&&(KGEN_x589)&&(defined KGENMACRO_CONFIG_VBNET_SAMPLES||(KGEN_x594)))))
#ifdef KGENMACRO_CONFIG_VBNET_SAMPLES
#define CONFIG_VBNET_SAMPLES 1
#else
#undef CONFIG_VBNET_SAMPLES
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_CSHARP_BINDINGS&&(KGEN_x474))||((KGEN_x487)&&(KGEN_x474)&&(defined KGENMACRO_CONFIG_CSHARP_SAMPLES||(KGEN_x487)))))
#ifdef KGENMACRO_CONFIG_CSHARP_SAMPLES
#define CONFIG_CSHARP_SAMPLES 1
#else
#undef CONFIG_CSHARP_SAMPLES
#endif
#endif
#if (((KGEN_x171)&&(KGEN_x172)))
#ifdef KGENMACRO_CONFIG_SSL_EXPIRY_TIME
#define CONFIG_SSL_EXPIRY_TIME 24
#else
#define CONFIG_SSL_EXPIRY_TIME 0
#endif
#endif
#if (((KGEN_x190)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_PERL_BINDINGS))))
#ifdef KGENMACRO_CONFIG_PERL_BINDINGS
#define CONFIG_PERL_BINDINGS 1
#else
#undef CONFIG_PERL_BINDINGS
#endif
#endif
#ifdef KGENMACRO_CONFIG_PLATFORM_WIN32
#define CONFIG_PLATFORM_WIN32 1
#else
#undef CONFIG_PLATFORM_WIN32
#endif
#if (defined KGENMACRO_CONFIG_SSL_MAX_CERTS)
#ifdef KGENMACRO_CONFIG_SSL_MAX_CERTS
#define CONFIG_SSL_MAX_CERTS 3
#else
#define CONFIG_SSL_MAX_CERTS 0
#endif
#endif
#if ((((KGEN_x84)&&((!defined KGENMACRO_CONFIG_AXTLSWRAP)||(KGEN_x84)))||(defined KGENMACRO_CONFIG_PLATFORM_WIN32&&(!defined KGENMACRO_CONFIG_AXTLSWRAP))))
#ifdef KGENMACRO_CONFIG_AXTLSWRAP
#define CONFIG_AXTLSWRAP 1
#else
#undef CONFIG_AXTLSWRAP
#endif
#endif
#if (defined KGENMACRO_CONFIG_EXTRA_CFLAGS_OPTIONS)
#ifdef KGENMACRO_CONFIG_EXTRA_CFLAGS_OPTIONS
#define CONFIG_EXTRA_CFLAGS_OPTIONS "X"
#else
#define CONFIG_EXTRA_CFLAGS_OPTIONS ""
#endif
#endif
#ifdef KGENMACRO_CONFIG_BIGINT_BARRETT
#define CONFIG_BIGINT_BARRETT 1
#else
#undef CONFIG_BIGINT_BARRETT
#endif
#ifdef KGENMACRO_UNAME_RELEASE
#define UNAME_RELEASE "5.4.0-139-generic"
#else
#define UNAME_RELEASE ""
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&(KGEN_x517))||((KGEN_x499)&&(KGEN_x517)&&(defined KGENMACRO_CONFIG_C_SAMPLES||(KGEN_x499)))))
#ifdef KGENMACRO_CONFIG_C_SAMPLES
#define CONFIG_C_SAMPLES 1
#else
#undef CONFIG_C_SAMPLES
#endif
#endif
#if (defined KGENMACRO_HAVE_DOT_CONFIG)
#ifdef KGENMACRO_HAVE_DOT_CONFIG
#define HAVE_DOT_CONFIG 1
#else
#undef HAVE_DOT_CONFIG
#endif
#endif
#if (((KGEN_x32)||(KGEN_x34))) && (((KGEN_x32)||(KGEN_x37)))
#ifdef KGENMACRO_CONFIG_BIGINT_CLASSICAL
#define CONFIG_BIGINT_CLASSICAL 1
#else
#undef CONFIG_BIGINT_CLASSICAL
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_JAVA_BINDINGS&&(KGEN_x162))||((KGEN_x164)&&(KGEN_x162)&&(defined KGENMACRO_CONFIG_JAVA_SAMPLES||(KGEN_x164)))))
#ifdef KGENMACRO_CONFIG_JAVA_SAMPLES
#define CONFIG_JAVA_SAMPLES 1
#else
#undef CONFIG_JAVA_SAMPLES
#endif
#endif
#if (((KGEN_x314)&&(KGEN_x316)))
#ifdef KGENMACRO_MUL_KARATSUBA_THRESH
#define MUL_KARATSUBA_THRESH 20
#else
#define MUL_KARATSUBA_THRESH 0
#endif
#endif
#ifdef KGENMACRO_CONFIG_DEBUG
#define CONFIG_DEBUG 1
#else
#undef CONFIG_DEBUG
#endif
#if (((KGEN_x324)&&(KGEN_x326)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_10_0_BASE
#define CONFIG_VISUAL_STUDIO_10_0_BASE "c:\\Program Files\\Microsoft Visual Studio 10.0"
#else
#define CONFIG_VISUAL_STUDIO_10_0_BASE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_LUA_BINDINGS&&(KGEN_x393))||((KGEN_x398)&&(KGEN_x393)&&(defined KGENMACRO_CONFIG_LUA_SAMPLES||(KGEN_x398)))))
#ifdef KGENMACRO_CONFIG_LUA_SAMPLES
#define CONFIG_LUA_SAMPLES 1
#else
#undef CONFIG_LUA_SAMPLES
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_SSL_PROT_MEDIUM)||(!defined KGENMACRO_CONFIG_SSL_PROT_HIGH)))
#ifdef KGENMACRO_CONFIG_SSL_PROT_MEDIUM
#define CONFIG_SSL_PROT_MEDIUM 1
#else
#undef CONFIG_SSL_PROT_MEDIUM
#endif
#endif
#ifdef KGENMACRO_CONFIG_AXHTTPD
#define CONFIG_AXHTTPD 1
#else
#undef CONFIG_AXHTTPD
#endif
#ifdef KGENMACRO_CONFIG_SSL_GENERATE_X509_CERT
#define CONFIG_SSL_GENERATE_X509_CERT 1
#else
#undef CONFIG_SSL_GENERATE_X509_CERT
#endif
#if ((((KGEN_x61)&&((KGEN_x61)||(!defined KGENMACRO_CONFIG_SSL_USE_PKCS12)))||(KGEN_x587)))
#ifdef KGENMACRO_CONFIG_SSL_USE_PKCS12
#define CONFIG_SSL_USE_PKCS12 1
#else
#undef CONFIG_SSL_USE_PKCS12
#endif
#endif
#if (((KGEN_x255)&&(KGEN_x257)))
#ifdef KGENMACRO_CONFIG_X509_MAX_CA_CERTS
#define CONFIG_X509_MAX_CA_CERTS 150
#else
#define CONFIG_X509_MAX_CA_CERTS 0
#endif
#endif
#if (((KGEN_x646)&&(KGEN_x647)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_8_0_BASE
#define CONFIG_VISUAL_STUDIO_8_0_BASE "c:\\Program Files\\Microsoft Visual Studio 8"
#else
#define CONFIG_VISUAL_STUDIO_8_0_BASE ""
#endif
#endif
#if (((KGEN_x665)&&(KGEN_x666)))
#ifdef KGENMACRO_PREFIX
#define PREFIX "/usr/local"
#else
#define PREFIX ""
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_VISUAL_STUDIO_8_0)||(!defined KGENMACRO_CONFIG_VISUAL_STUDIO_10_0)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_8_0
#define CONFIG_VISUAL_STUDIO_8_0 1
#else
#undef CONFIG_VISUAL_STUDIO_8_0
#endif
#endif
#if (((KGEN_x628)&&(KGEN_x632)))
#ifdef KGENMACRO_CONFIG_SSL_X509_CERT_LOCATION
#define CONFIG_SSL_X509_CERT_LOCATION "X"
#else
#define CONFIG_SSL_X509_CERT_LOCATION ""
#endif
#endif
#if (((KGEN_x493)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_VBNET_BINDINGS))))
#ifdef KGENMACRO_CONFIG_VBNET_BINDINGS
#define CONFIG_VBNET_BINDINGS 1
#else
#undef CONFIG_VBNET_BINDINGS
#endif
#endif
#if (((KGEN_x58)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_FULL_MODE
#define CONFIG_SSL_FULL_MODE 1
#else
#undef CONFIG_SSL_FULL_MODE
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_BIGINT_MONTGOMERY)||(!defined KGENMACRO_CONFIG_BIGINT_BARRETT)))
#ifdef KGENMACRO_CONFIG_BIGINT_MONTGOMERY
#define CONFIG_BIGINT_MONTGOMERY 1
#else
#undef CONFIG_BIGINT_MONTGOMERY
#endif
#endif
#if (((KGEN_x271)&&(KGEN_x274)))
#ifdef KGENMACRO_CONFIG_HTTP_PORT
#define CONFIG_HTTP_PORT 80
#else
#define CONFIG_HTTP_PORT 0
#endif
#endif
#if (((KGEN_x363)&&(KGEN_x366)))
#ifdef KGENMACRO_CONFIG_HTTP_HTTPS_PORT
#define CONFIG_HTTP_HTTPS_PORT 443
#else
#define CONFIG_HTTP_HTTPS_PORT 0
#endif
#endif
#ifdef KGENMACRO_CONFIG_SSL_CTX_MUTEXING
#define CONFIG_SSL_CTX_MUTEXING 1
#else
#undef CONFIG_SSL_CTX_MUTEXING
#endif
#if (((KGEN_x384)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_CSHARP_BINDINGS))))
#ifdef KGENMACRO_CONFIG_CSHARP_BINDINGS
#define CONFIG_CSHARP_BINDINGS 1
#else
#undef CONFIG_CSHARP_BINDINGS
#endif
#endif
#if (((KGEN_x527)&&(KGEN_x528)))
#ifdef KGENMACRO_CONFIG_HTTP_LUA_PREFIX
#define CONFIG_HTTP_LUA_PREFIX "/usr"
#else
#define CONFIG_HTTP_LUA_PREFIX ""
#endif
#endif
#ifdef KGENMACRO_CONFIG_SSL_SKELETON_MODE
#define CONFIG_SSL_SKELETON_MODE 1
#else
#undef CONFIG_SSL_SKELETON_MODE
#endif
#if ((((KGEN_x61)&&(KGEN_x555))||(KGEN_x580)))
#ifdef KGENMACRO_CONFIG_BIGINT_SQUARE
#define CONFIG_BIGINT_SQUARE 1
#else
#undef CONFIG_BIGINT_SQUARE
#endif
#endif
#if ((((KGEN_x84)&&(KGEN_x360))||(KGEN_x364)))
#ifdef KGENMACRO_CONFIG_USE_DEV_URANDOM
#define CONFIG_USE_DEV_URANDOM 1
#else
#undef CONFIG_USE_DEV_URANDOM
#endif
#endif
#if (((defined KGENMACRO_CONFIG_SAMPLES&&defined KGENMACRO_CONFIG_PERL_BINDINGS&&(KGEN_x177))||((KGEN_x181)&&(KGEN_x177)&&(defined KGENMACRO_CONFIG_PERL_SAMPLES||(KGEN_x181)))))
#ifdef KGENMACRO_CONFIG_PERL_SAMPLES
#define CONFIG_PERL_SAMPLES 1
#else
#undef CONFIG_PERL_SAMPLES
#endif
#endif
#if (((KGEN_x591)||((!(KGEN_x110))&&(KGEN_x566))))
#ifdef KGENMACRO_CONFIG_HTTP_BUILD_LUA
#define CONFIG_HTTP_BUILD_LUA 1
#else
#undef CONFIG_HTTP_BUILD_LUA
#endif
#endif
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_10_0
#define CONFIG_VISUAL_STUDIO_10_0 1
#else
#undef CONFIG_VISUAL_STUDIO_10_0
#endif
#if (((KGEN_x706)||((!defined KGENMACRO_CONFIG_SSL_CERT_VERIFICATION)&&(KGEN_x678))))
#ifdef KGENMACRO_CONFIG_PERFORMANCE_TESTING
#define CONFIG_PERFORMANCE_TESTING 1
#else
#undef CONFIG_PERFORMANCE_TESTING
#endif
#endif
#if (((KGEN_x618)&&(KGEN_x619)))
#ifdef KGENMACRO_SQU_KARATSUBA_THRESH
#define SQU_KARATSUBA_THRESH 40
#else
#define SQU_KARATSUBA_THRESH 0
#endif
#endif
#if (defined KGENMACRO_CONFIG_EXTRA_LDFLAGS_OPTIONS)
#ifdef KGENMACRO_CONFIG_EXTRA_LDFLAGS_OPTIONS
#define CONFIG_EXTRA_LDFLAGS_OPTIONS "X"
#else
#define CONFIG_EXTRA_LDFLAGS_OPTIONS ""
#endif
#endif
#if ((((KGEN_x84)&&(KGEN_x635)&&(KGEN_x663))||((KGEN_x668)&&(KGEN_x663)&&(defined KGENMACRO_CONFIG_STRIP_UNWANTED_SECTIONS||(KGEN_x668)))))
#ifdef KGENMACRO_CONFIG_STRIP_UNWANTED_SECTIONS
#define CONFIG_STRIP_UNWANTED_SECTIONS 1
#else
#undef CONFIG_STRIP_UNWANTED_SECTIONS
#endif
#endif
#if (((KGEN_x55)||(KGEN_x58))) && (((KGEN_x55)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_ENABLE_CLIENT
#define CONFIG_SSL_ENABLE_CLIENT 1
#else
#undef CONFIG_SSL_ENABLE_CLIENT
#endif
#endif
#if ((((KGEN_x61)&&(KGEN_x289))||(KGEN_x293)))
#ifdef KGENMACRO_CONFIG_SSL_USE_DEFAULT_KEY
#define CONFIG_SSL_USE_DEFAULT_KEY 1
#else
#undef CONFIG_SSL_USE_DEFAULT_KEY
#endif
#endif
#if (((KGEN_x52)||(KGEN_x55))) && (((KGEN_x52)||(KGEN_x58))) && (((KGEN_x52)||(KGEN_x61)))
#ifdef KGENMACRO_CONFIG_SSL_CERT_VERIFICATION
#define CONFIG_SSL_CERT_VERIFICATION 1
#else
#undef CONFIG_SSL_CERT_VERIFICATION
#endif
#endif
#if (((KGEN_x613)&&(KGEN_x614)))
#ifdef KGENMACRO_CONFIG_HTTP_WEBROOT
#define CONFIG_HTTP_WEBROOT "..\\www"
#else
#define CONFIG_HTTP_WEBROOT ""
#endif
#endif
#if (((KGEN_x412)||((!defined KGENMACRO_CONFIG_AXHTTPD)&&(!defined KGENMACRO_CONFIG_HTTP_STATIC_BUILD))))
#ifdef KGENMACRO_CONFIG_HTTP_STATIC_BUILD
#define CONFIG_HTTP_STATIC_BUILD 1
#else
#undef CONFIG_HTTP_STATIC_BUILD
#endif
#endif
#if (((KGEN_x230)&&(KGEN_x234)))
#ifdef KGENMACRO_CONFIG_HTTP_SESSION_CACHE_SIZE
#define CONFIG_HTTP_SESSION_CACHE_SIZE 5
#else
#define CONFIG_HTTP_SESSION_CACHE_SIZE 0
#endif
#endif
#if (((KGEN_x604)&&(KGEN_x605)))
#ifdef KGENMACRO_CONFIG_HTTP_CGI_EXTENSIONS
#define CONFIG_HTTP_CGI_EXTENSIONS ".lua,.lp,.php"
#else
#define CONFIG_HTTP_CGI_EXTENSIONS ""
#endif
#endif
#ifdef KGENMACRO_CONFIG_OPENSSL_COMPATIBLE
#define CONFIG_OPENSSL_COMPATIBLE 1
#else
#undef CONFIG_OPENSSL_COMPATIBLE
#endif
#if ((((KGEN_x61)&&(KGEN_x420))||(KGEN_x452)))
#ifdef KGENMACRO_CONFIG_BIGINT_SLIDING_WINDOW
#define CONFIG_BIGINT_SLIDING_WINDOW 1
#else
#undef CONFIG_BIGINT_SLIDING_WINDOW
#endif
#endif
#if (((KGEN_x70)||(KGEN_x72))) && (((KGEN_x70)||(KGEN_x75)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_7_0
#define CONFIG_VISUAL_STUDIO_7_0 1
#else
#undef CONFIG_VISUAL_STUDIO_7_0
#endif
#endif
#if ((((KGEN_x61)&&((KGEN_x312)||(KGEN_x61)))||(defined KGENMACRO_CONFIG_SSL_SKELETON_MODE&&(KGEN_x312))))
#ifdef KGENMACRO_CONFIG_BIGINT_KARATSUBA
#define CONFIG_BIGINT_KARATSUBA 1
#else
#undef CONFIG_BIGINT_KARATSUBA
#endif
#endif
#if ((((KGEN_x61)&&(KGEN_x460))||(KGEN_x488)))
#ifdef KGENMACRO_CONFIG_BIGINT_CRT
#define CONFIG_BIGINT_CRT 1
#else
#undef CONFIG_BIGINT_CRT
#endif
#endif
#if (((KGEN_x147)&&(KGEN_x149)))
#ifdef KGENMACRO_CONFIG_HTTP_USER
#define CONFIG_HTTP_USER "nobody"
#else
#define CONFIG_HTTP_USER ""
#endif
#endif
#if (((KGEN_x378)&&(KGEN_x380)))
#ifdef KGENMACRO_CONFIG_LUA_CORE
#define CONFIG_LUA_CORE "/usr/local"
#else
#define CONFIG_LUA_CORE ""
#endif
#endif
#if (((KGEN_x577)&&(KGEN_x579)))
#ifdef KGENMACRO_CONFIG_VISUAL_STUDIO_7_0_BASE
#define CONFIG_VISUAL_STUDIO_7_0_BASE "c:\\Program Files\\Microsoft Visual Studio .NET 2003"
#else
#define CONFIG_VISUAL_STUDIO_7_0_BASE ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&(KGEN_x253))||((KGEN_x132)&&(KGEN_x253)&&(defined KGENMACRO_CONFIG_HTTP_HAS_CGI||(KGEN_x132)))))
#ifdef KGENMACRO_CONFIG_HTTP_HAS_CGI
#define CONFIG_HTTP_HAS_CGI 1
#else
#undef CONFIG_HTTP_HAS_CGI
#endif
#endif
#if (((KGEN_x557)&&(KGEN_x558)))
#ifdef KGENMACRO_CONFIG_PERL_LIB
#define CONFIG_PERL_LIB "perl58.lib"
#else
#define CONFIG_PERL_LIB ""
#endif
#endif
#if (((KGEN_x23)||(KGEN_x25))) && (((KGEN_x23)||(KGEN_x28)))
#ifdef KGENMACRO_CONFIG_INTEGER_32BIT
#define CONFIG_INTEGER_32BIT 1
#else
#undef CONFIG_INTEGER_32BIT
#endif
#endif
#ifdef KGENMACRO_CONFIG_BINDINGS
#define CONFIG_BINDINGS 1
#else
#undef CONFIG_BINDINGS
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&((KGEN_x267)||(KGEN_x123)))||(KGEN_x297)))
#ifdef KGENMACRO_CONFIG_HTTP_HAS_IPV6
#define CONFIG_HTTP_HAS_IPV6 1
#else
#undef CONFIG_HTTP_HAS_IPV6
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_PLATFORM_CYGWIN)||(KGEN_x84)))
#ifdef KGENMACRO_CONFIG_PLATFORM_CYGWIN
#define CONFIG_PLATFORM_CYGWIN 1
#else
#undef CONFIG_PLATFORM_CYGWIN
#endif
#endif
#if (((KGEN_x261)&&(KGEN_x262)))
#ifdef KGENMACRO_CONFIG_SSL_PRIVATE_KEY_LOCATION
#define CONFIG_SSL_PRIVATE_KEY_LOCATION "X"
#else
#define CONFIG_SSL_PRIVATE_KEY_LOCATION ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_BINDINGS&&(KGEN_x84)&&((KGEN_x379)||(KGEN_x610)))||(KGEN_x637)))
#ifdef KGENMACRO_CONFIG_LUA_BINDINGS
#define CONFIG_LUA_BINDINGS 1
#else
#undef CONFIG_LUA_BINDINGS
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x425))||((KGEN_x218)&&(KGEN_x425)&&((KGEN_x218)||defined KGENMACRO_CONFIG_HTTP_HAS_AUTHORIZATION))))
#ifdef KGENMACRO_CONFIG_HTTP_HAS_AUTHORIZATION
#define CONFIG_HTTP_HAS_AUTHORIZATION 1
#else
#undef CONFIG_HTTP_HAS_AUTHORIZATION
#endif
#endif
#ifdef KGENMACRO_CONFIG_INTEGER_8BIT
#define CONFIG_INTEGER_8BIT 1
#else
#undef CONFIG_INTEGER_8BIT
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&defined KGENMACRO_CONFIG_HTTP_HAS_CGI&&(KGEN_x118))||((KGEN_x120)&&(KGEN_x118)&&(defined KGENMACRO_CONFIG_HTTP_ENABLE_LUA||(KGEN_x120)))))
#ifdef KGENMACRO_CONFIG_HTTP_ENABLE_LUA
#define CONFIG_HTTP_ENABLE_LUA 1
#else
#undef CONFIG_HTTP_ENABLE_LUA
#endif
#endif
#if (((KGEN_x437)||((!defined KGENMACRO_CONFIG_BINDINGS)&&(!defined KGENMACRO_CONFIG_JAVA_BINDINGS))))
#ifdef KGENMACRO_CONFIG_JAVA_BINDINGS
#define CONFIG_JAVA_BINDINGS 1
#else
#undef CONFIG_JAVA_BINDINGS
#endif
#endif
#if (((KGEN_x532)&&(KGEN_x533)))
#ifdef KGENMACRO_CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME "X"
#else
#define CONFIG_SSL_X509_ORGANIZATION_UNIT_NAME ""
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&((KGEN_x129)||(KGEN_x123)))||((KGEN_x132)&&(KGEN_x129))))
#ifdef KGENMACRO_CONFIG_HTTP_ENABLE_DIFFERENT_USER
#define CONFIG_HTTP_ENABLE_DIFFERENT_USER 1
#else
#undef CONFIG_HTTP_ENABLE_DIFFERENT_USER
#endif
#endif
#if ((((KGEN_x61)&&((!defined KGENMACRO_CONFIG_BIGINT_CHECK_ON)||(KGEN_x61)))||(KGEN_x661)))
#ifdef KGENMACRO_CONFIG_BIGINT_CHECK_ON
#define CONFIG_BIGINT_CHECK_ON 1
#else
#undef CONFIG_BIGINT_CHECK_ON
#endif
#endif
#if (((!defined KGENMACRO_CONFIG_INTEGER_16BIT)||(!defined KGENMACRO_CONFIG_INTEGER_8BIT)))
#ifdef KGENMACRO_CONFIG_INTEGER_16BIT
#define CONFIG_INTEGER_16BIT 1
#else
#undef CONFIG_INTEGER_16BIT
#endif
#endif
#ifdef KGENMACRO_CONFIG_SAMPLES
#define CONFIG_SAMPLES 1
#else
#undef CONFIG_SAMPLES
#endif
#if (((KGEN_x245)&&(KGEN_x247)))
#ifdef KGENMACRO_CONFIG_SSL_X509_COMMON_NAME
#define CONFIG_SSL_X509_COMMON_NAME "X"
#else
#define CONFIG_SSL_X509_COMMON_NAME ""
#endif
#endif
#if (((KGEN_x79)||(KGEN_x81))) && (((KGEN_x79)||(KGEN_x84)))
#ifdef KGENMACRO_CONFIG_PLATFORM_LINUX
#define CONFIG_PLATFORM_LINUX 1
#else
#undef CONFIG_PLATFORM_LINUX
#endif
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(KGEN_x84)&&((KGEN_x223)||(KGEN_x123)))||((KGEN_x132)&&(KGEN_x223))))
#ifdef KGENMACRO_CONFIG_HTTP_IS_DAEMON
#define CONFIG_HTTP_IS_DAEMON 1
#else
#undef CONFIG_HTTP_IS_DAEMON
#endif
#endif
#ifdef KGENMACRO_CONFIG_SSL_PROT_HIGH
#define CONFIG_SSL_PROT_HIGH 1
#else
#undef CONFIG_SSL_PROT_HIGH
#endif
#if (((defined KGENMACRO_CONFIG_AXHTTPD&&(defined KGENMACRO_CONFIG_AXHTTPD||(KGEN_x447)))||((KGEN_x218)&&((KGEN_x447)||(KGEN_x451))&&(KGEN_x480))))
#ifdef KGENMACRO_CONFIG_HTTP_VERBOSE
#define CONFIG_HTTP_VERBOSE 1
#else
#undef CONFIG_HTTP_VERBOSE
#endif
#endif
#if ((((KGEN_x61)&&((!defined KGENMACRO_CONFIG_SSL_HAS_PEM)||(KGEN_x61)))||(KGEN_x567)))
#ifdef KGENMACRO_CONFIG_SSL_HAS_PEM
#define CONFIG_SSL_HAS_PEM 1
#else
#undef CONFIG_SSL_HAS_PEM
#endif
#endif
#if (((KGEN_x514)&&(KGEN_x515)))
#ifdef KGENMACRO_CONFIG_HTTP_CGI_LAUNCHER
#define CONFIG_HTTP_CGI_LAUNCHER "/usr/bin/cgi"
#else
#define CONFIG_HTTP_CGI_LAUNCHER ""
#endif
#endif
#if (((KGEN_x478)&&(KGEN_x484)))
#ifdef KGENMACRO_CONFIG_SSL_PRIVATE_KEY_PASSWORD
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD "X"
#else
#define CONFIG_SSL_PRIVATE_KEY_PASSWORD ""
#endif
#endif
#if (((KGEN_x547)||((KGEN_x84)&&(KGEN_x530))))
#ifdef KGENMACRO_CONFIG_WIN32_USE_CRYPTO_LIB
#define CONFIG_WIN32_USE_CRYPTO_LIB 1
#else
#undef CONFIG_WIN32_USE_CRYPTO_LIB
#endif
#endif
