FROM sugarlyzer/base

ENV VERSION=1.1.0
RUN curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" \
	| tar -C /opt -xJ && ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer

COPY tester.jar /app/tester.jar

WORKDIR /
