#undef _LIBC         
#undef _GLIBCPP_USE_WCHAR_T 
#undef __cplusplus   
#undef _BSD_VA_LIST  
#undef __svr4__      
#undef _SCO_DS       
#undef __i860__      
#undef __BSD_NET2_   
#undef ____386BSD____
#undef __bsdi__      
#undef __sequent__   
#undef __FreeBSD__   
#undef WINNT         
#undef __ASSEMBLER__ 
#undef _LOOSE_KERNEL_NAMES        
#undef __GXX_EXPERIMENTAL_CXX0X__ 
#undef __ILP32__        
#undef __GNUG__         
#undef __LONG_DOUBLE_MATH_OPTIONAL
#undef __NO_LONG_DOUBLE_MATH      
#undef __sys_stdtypes_h  
#undef __NetBSD__        
#undef _TYPE_ptrdiff_t   
#undef _TYPE_size_t      
#undef _TYPE_wchar_t     
#undef _PTRDIFF_T        
#undef _T_PTRDIFF_       
#undef _T_PTRDIFF        
#undef __PTRDIFF_T       
#undef _PTRDIFF_T_       
#undef _BSD_PTRDIFF_T_   
#undef ___int_ptrdiff_t_h   
#undef _GCC_PTRDIFF_T       
#undef _PTRDIFF_T_DECLARED  
#undef __size_t__     
#undef __SIZE_T__     
#undef _SIZE_T        
#undef _SYS_SIZE_T_H  
#undef _T_SIZE_       
#undef _T_SIZE        
#undef __SIZE_T       
#undef _SIZE_T_       
#undef _BSD_SIZE_T_   
#undef _SIZE_T_DEFINED_     
#undef _SIZE_T_DEFINED      
#undef _BSD_SIZE_T_DEFINED_ 
#undef _SIZE_T_DECLARED     
#undef ___int_size_t_h 
#undef _GCC_SIZE_T     
#undef _SIZET_         
#undef __wchar_t__     
#undef __WCHAR_T__     
#undef _WCHAR_T        
#undef _T_WCHAR_       
#undef _T_WCHAR        
#undef __WCHAR_T       
#undef _WCHAR_T_       
#undef _BSD_WCHAR_T_   
#undef _BSD_WCHAR_T_DEFINED_
#undef _BSD_RUNE_T_DEFINED_ 
#undef _WCHAR_T_DEFINED_    
#undef _WCHAR_T_DEFINED     
#undef _WCHAR_T_H       
#undef ___int_wchar_t_h 
#undef __INT_WCHAR_T_H  
#undef _GCC_WCHAR_T     
#undef _WCHAR_T_DECLARED
#undef _BSD_RUNE_T_     
#undef __BSD_VISIBLE    
#undef _GCC_PTRDIFF_T_  
#undef _GCC_SIZE_T_     
#undef _GCC_WCHAR_T_    
#undef __i386__
#undef i386
#undef __i486__         
#undef __pentium__      
#undef __pentiumpro__   
#undef __pentium4__     
#undef __athlon__    
#undef __k6__        
#undef __nocona__    
#undef __core2__     
#undef __geode__     
#undef __amdfam10__  
#undef __need_Emath  
#undef __need_error_t
#undef SHARED        
#undef _CRAY         
#undef __BEOS__         
#undef _HAVE_STRING_ARCH_mempcpy  
#define __NO_CTYPE 1    
#undef __LDBL_COMPAT
#undef __clang__
#undef WIN32
#undef _WIN32_WCE
#undef _ISOC99_SOURCE
#undef _ISOC11_SOURCE
#undef _POSIX_SOURCE
#undef _POSIX_C_SOURCE
#undef _XOPEN_SOURCE
#undef _XOPEN_SOURCE_EXTENDED
#undef _LARGEFILE_SOURCE
#undef _LARGEFILE64_SOURCE
#undef _ATFILE_SOURCE
#undef _GNU_SOURCE
#undef _DEFAULT_SOURCE
#undef _BSD_SOURCE
#undef _SVID_SOURCE
#undef _WIN32
#undef _WIN32_WCE
#undef __WIN32__
#undef _WIN64
#undef _Mfloat_
#undef _Mlong_double_
#undef RE_DUP_MAX
#undef RE_TRANSLATE_TYPE
#undef RE_NREGS
#undef _REGEX_RE_COMP
#undef __CORRECT_ISO_CPP_WCHAR_H_PROTO
#undef __digital__
#undef __OpenBSD__
#undef __APPLE__
#undef __powerpc__
#undef __mips__
#undef __cris__
#undef ANDROID
#undef __ANDROID__
#undef __CYGWIN__
#define __wur
